// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/pkg/models/shared"
)

type CancelIntentRequest struct {
	// The ID of the intent
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type CancelIntentResponse struct {
	ContentType string
	// Intent cancellation successful
	Intent      *shared.Intent
	StatusCode  int
	RawResponse *http.Response
	// Error
	Error *shared.Error
}
