// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/v2/pkg/models/shared"
)

type CancelIntentRequest struct {
	// The ID of the intent
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *CancelIntentRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CancelIntentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Intent cancellation successful
	Intent *shared.Intent
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (o *CancelIntentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelIntentResponse) GetIntent() *shared.Intent {
	if o == nil {
		return nil
	}
	return o.Intent
}

func (o *CancelIntentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelIntentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CancelIntentResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
