// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/pkg/models/shared"
)

type CreateUserRequest struct {
	CreateUserRequest shared.CreateUserRequest `request:"mediaType=application/json"`
	// The idempotency key for the request
	XIdempotencyKey string `header:"style=simple,explode=false,name=X-Idempotency-Key"`
}

type CreateUserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// User created successfully
	User *shared.User
	// Error
	Error *shared.Error
}
