// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/pkg/models/shared"
)

type GetBalanceResponse struct {
	// Account balance retrieved successfully
	AccountBalance *shared.AccountBalance
	ContentType    string
	StatusCode     int
	RawResponse    *http.Response
	// Error
	Error *shared.Error
}
