// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/pkg/models/shared"
)

type GetEventRequest struct {
	// The ID of the event to retrieve
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetEventResponse struct {
	ContentType string
	// Successful operation
	Event       *shared.Event
	StatusCode  int
	RawResponse *http.Response
	// Error
	Error *shared.Error
}
