// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/v3/pkg/models/shared"
)

type GetIntentRequest struct {
	// The intent ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetIntentRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetIntentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// successful operation
	Intent *shared.Intent
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (o *GetIntentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetIntentResponse) GetIntent() *shared.Intent {
	if o == nil {
		return nil
	}
	return o.Intent
}

func (o *GetIntentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetIntentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetIntentResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
