// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/pkg/models/shared"
)

type GetIntentRequest struct {
	// The intent ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetIntentResponse struct {
	ContentType string
	// successful operation
	Intent      *shared.Intent
	StatusCode  int
	RawResponse *http.Response
	// Error
	Error *shared.Error
}
