// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/pkg/models/shared"
)

type GetTransferRequest struct {
	// The ID of the transfer to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetTransferResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful operation
	Transfer *shared.Transfer
	// Error
	Error *shared.Error
}
