// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/v3/pkg/models/shared"
)

type GetTransferRequest struct {
	// The ID of the transfer to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetTransferRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetTransferResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful operation
	Transfer *shared.Transfer
	// Error
	Error *shared.Error
}

func (o *GetTransferResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTransferResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTransferResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTransferResponse) GetTransfer() *shared.Transfer {
	if o == nil {
		return nil
	}
	return o.Transfer
}

func (o *GetTransferResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
