// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/pkg/models/shared"
)

type GetTransactionRequest struct {
	// The ID of the transaction to retrieve.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetTransactionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful operation
	Transaction *shared.Transaction
	// Error
	Error *shared.Error
}
