// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/v3/pkg/models/shared"
)

type GetUserRequest struct {
	// The push identifier for the user
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetUserRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	User *shared.User
	// Error
	Error *shared.Error
}

func (o *GetUserResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetUserResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetUserResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetUserResponse) GetUser() *shared.User {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *GetUserResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
