// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/v3/pkg/models/shared"
)

type UpdateUserRequest struct {
	UpdateUserRequest *shared.UpdateUserRequest `request:"mediaType=application/json"`
	// The ID of the user to update.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateUserRequest) GetUpdateUserRequest() *shared.UpdateUserRequest {
	if o == nil {
		return nil
	}
	return o.UpdateUserRequest
}

func (o *UpdateUserRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UpdateUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User update successful
	User *shared.User
	// Error
	Error *shared.Error
}

func (o *UpdateUserResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateUserResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateUserResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateUserResponse) GetUser() *shared.User {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *UpdateUserResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
