// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"push-cash/pkg/models/shared"
)

type UpdateUserRequest struct {
	UpdateUserRequest *shared.UpdateUserRequest `request:"mediaType=application/json"`
	// The ID of the user to update.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateUserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// User update successful
	User *shared.User
	// Error
	Error *shared.Error
}
