// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AccountBalance - Account balance retrieved successfully
type AccountBalance struct {
	// Funds that are available to be transferred to your primary business checking account,
	// or used to fund your users “cash-out” transactions.
	//
	Available int64 `json:"available"`
	// Currency associated with the amount
	Currency Currency `json:"currency"`
	// Funds that are not yet available to be used for a bank_transfer or used for cash_out.
	// Examples of transactions that would impact this balance type include pending bank_transfers
	// (e.g. ACH credit not yet initiated, ACH debit has not yet settled).
	//
	Pending int64 `json:"pending"`
}

func (o *AccountBalance) GetAvailable() int64 {
	if o == nil {
		return 0
	}
	return o.Available
}

func (o *AccountBalance) GetCurrency() Currency {
	if o == nil {
		return Currency("")
	}
	return o.Currency
}

func (o *AccountBalance) GetPending() int64 {
	if o == nil {
		return 0
	}
	return o.Pending
}
