// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateIntentRequest struct {
	// amount (in cents) for the transaction
	Amount int64 `json:"amount"`
	// Currency associated with the amount
	Currency Currency `json:"currency"`
	// Direction of the money
	Direction Direction `json:"direction"`
	// Push's unique identifier for the user
	UserID string `json:"user_id"`
}

func (o *CreateIntentRequest) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *CreateIntentRequest) GetCurrency() Currency {
	if o == nil {
		return Currency("")
	}
	return o.Currency
}

func (o *CreateIntentRequest) GetDirection() Direction {
	if o == nil {
		return Direction("")
	}
	return o.Direction
}

func (o *CreateIntentRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
