// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"push-cash/pkg/utils"
)

type CreateTransferRequest struct {
	// amount (in cents) for the transaction
	Amount int64 `json:"amount"`
	// Currency associated with the amount
	currency string `const:"USD" json:"currency"`
	// Direction of the money
	Direction Direction `json:"direction"`
}

func (c CreateTransferRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTransferRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateTransferRequest) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *CreateTransferRequest) GetCurrency() string {
	return "USD"
}

func (o *CreateTransferRequest) GetDirection() Direction {
	if o == nil {
		return Direction("")
	}
	return o.Direction
}
