// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"push-cash/pkg/utils"
)

type CreateIntentRequest struct {
	// amount (in cents) for the transaction
	Amount int64 `json:"amount"`
	// Currency associated with the amount
	currency string `const:"USD" json:"currency"`
	// Direction of the money
	Direction Direction `json:"direction"`
	// Push's unique identifier for the user
	UserID string `json:"user_id"`
}

func (c CreateIntentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateIntentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateIntentRequest) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *CreateIntentRequest) GetCurrency() string {
	return "USD"
}

func (o *CreateIntentRequest) GetDirection() Direction {
	if o == nil {
		return Direction("")
	}
	return o.Direction
}

func (o *CreateIntentRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
