// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateTransferRequest struct {
	// amount (in cents) for the transaction
	Amount int64 `json:"amount"`
	// Currency associated with the amount
	Currency Currency `json:"currency"`
	// Direction of the money
	Direction Direction `json:"direction"`
}

func (o *CreateTransferRequest) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *CreateTransferRequest) GetCurrency() Currency {
	if o == nil {
		return Currency("")
	}
	return o.Currency
}

func (o *CreateTransferRequest) GetDirection() Direction {
	if o == nil {
		return Direction("")
	}
	return o.Direction
}
