// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// EventEventType - the type of event indicates how the status of the resource has changed
type EventEventType string

const (
	EventEventTypeIntentProcessed      EventEventType = "intent.processed"
	EventEventTypeIntentChargedback    EventEventType = "intent.chargedback"
	EventEventTypeTransactionAvailable EventEventType = "transaction.available"
)

func (e EventEventType) ToPointer() *EventEventType {
	return &e
}

func (e *EventEventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "intent.processed":
		fallthrough
	case "intent.chargedback":
		fallthrough
	case "transaction.available":
		*e = EventEventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EventEventType: %v", v)
	}
}

// EventSourceType - the type of the resource which has been updated
type EventSourceType string

const (
	EventSourceTypeIntent      EventSourceType = "intent"
	EventSourceTypeTransaction EventSourceType = "transaction"
)

func (e EventSourceType) ToPointer() *EventSourceType {
	return &e
}

func (e *EventSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "intent":
		fallthrough
	case "transaction":
		*e = EventSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EventSourceType: %v", v)
	}
}

// Event - Successful operation
type Event struct {
	// when the event occurred
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// the type of event indicates how the status of the resource has changed
	EventType EventEventType `json:"event_type"`
	// the identifier for the event
	ID string `json:"id"`
	// the identifier of the resource who's status has updated
	SourceID string `json:"source_id"`
	// the type of the resource which has been updated
	SourceType EventSourceType `json:"source_type"`
}
