// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"push-cash/pkg/utils"
	"time"
)

// IntentFailureDetails - Failure details is non-null only for 'declined', 'error', 'timedout', 'chargedback'
type IntentFailureDetails struct {
	// The failure code
	Code int64 `json:"code"`
	// Description of the failure
	Description string `json:"description"`
}

func (o *IntentFailureDetails) GetCode() int64 {
	if o == nil {
		return 0
	}
	return o.Code
}

func (o *IntentFailureDetails) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

type Intent struct {
	// amount (in cents) for the transaction
	Amount int64 `json:"amount"`
	// Creation timestamp for the Intent
	CreatedAt time.Time `json:"created_at"`
	// Currency associated with the amount
	currency string `const:"USD" json:"currency"`
	// Direction of the money
	Direction Direction `json:"direction"`
	// Failure details is non-null only for 'declined', 'error', 'timedout', 'chargedback'
	FailureDetails *IntentFailureDetails `json:"failure_details"`
	ID             string                `json:"id"`
	Status         IntentStatus          `json:"status"`
	UserID         string                `json:"user_id"`
}

func (i Intent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Intent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Intent) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *Intent) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Intent) GetCurrency() string {
	return "USD"
}

func (o *Intent) GetDirection() Direction {
	if o == nil {
		return Direction("")
	}
	return o.Direction
}

func (o *Intent) GetFailureDetails() *IntentFailureDetails {
	if o == nil {
		return nil
	}
	return o.FailureDetails
}

func (o *Intent) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Intent) GetStatus() IntentStatus {
	if o == nil {
		return IntentStatus("")
	}
	return o.Status
}

func (o *Intent) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
