// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// IntentFailureDetails - Failure details is non-null only for 'declined', 'error', 'timedout', 'chargedback'
type IntentFailureDetails struct {
	// The failure code
	Code int64 `json:"code"`
	// Description of the failure
	Description string `json:"description"`
}

// Intent - successful operation
type Intent struct {
	// amount (in cents) for the transaction
	Amount int64 `json:"amount"`
	// Creation timestamp for the Intent
	CreatedAt time.Time `json:"created_at"`
	// Currency associated with the amount
	Currency Currency `json:"currency"`
	// Direction of the money
	Direction Direction `json:"direction"`
	// Failure details is non-null only for 'declined', 'error', 'timedout', 'chargedback'
	FailureDetails IntentFailureDetails `json:"failure_details"`
	ID             string               `json:"id"`
	Status         IntentStatus         `json:"status"`
	UserID         string               `json:"user_id"`
}
