// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"push-cash/pkg/utils"
)

type Kyc struct {
	// The KYC provider
	method string `const:"alloy" json:"method"`
	// the token representing the user entity at your KYC provider
	Token string `json:"token"`
}

func (k Kyc) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *Kyc) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Kyc) GetMethod() string {
	return "alloy"
}

func (o *Kyc) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
