// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Method - The KYC provider
type Method string

const (
	MethodAlloy Method = "alloy"
)

func (e Method) ToPointer() *Method {
	return &e
}

func (e *Method) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "alloy":
		*e = Method(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Method: %v", v)
	}
}

type Kyc struct {
	// The KYC provider
	Method Method `json:"method"`
	// the token representing the user entity at your KYC provider
	Token string `json:"token"`
}

func (o *Kyc) GetMethod() Method {
	if o == nil {
		return Method("")
	}
	return o.Method
}

func (o *Kyc) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
