// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"push-cash/pkg/types"
	"time"
)

type PaymentCredentialAccount struct {
	// the account number (mask)
	NumberMask string `json:"number_mask"`
	// the routing number for the account
	Routing string `json:"routing"`
}

type PaymentCredentialCard struct {
	// the expiration date for the card
	Expiration types.Date `json:"expiration"`
	// the primary account number (mask)
	PrimaryAccountNumberMask string `json:"primary_account_number_mask"`
}

// PaymentCredential - The array will be empty until the user completes their first transaction. Additional transactions will utilize stored payment credentials
type PaymentCredential struct {
	Account PaymentCredentialAccount `json:"account"`
	// the name of the bank associated with the credential
	BankName string                `json:"bank_name"`
	Card     PaymentCredentialCard `json:"card"`
	// Datetime for when the payment credential was created for the user
	CreatedAt time.Time `json:"created_at"`
}
