// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TransactionStatus - Indicates how the funds from the transaction are represented in the account balance
type TransactionStatus string

const (
	TransactionStatusPending   TransactionStatus = "pending"
	TransactionStatusAvailable TransactionStatus = "available"
)

func (e TransactionStatus) ToPointer() *TransactionStatus {
	return &e
}

func (e *TransactionStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "available":
		*e = TransactionStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TransactionStatus: %v", v)
	}
}
