// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"push-cash/pkg/types"
)

type Transfer struct {
	// Amount of the transfer
	Amount int64 `json:"amount"`
	// Date the funds will arrive, formatted "YYYY-MM-DD"
	ArrivalDate types.Date `json:"arrival_date"`
	// Currency associated with the amount
	Currency Currency `json:"currency"`
	// Direction of the money
	Direction Direction `json:"direction"`
	// The unique identifier assigned by Push, prefix is "transfer_"
	ID     string         `json:"id"`
	Status TransferStatus `json:"status"`
}

func (o *Transfer) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *Transfer) GetArrivalDate() types.Date {
	if o == nil {
		return types.Date{}
	}
	return o.ArrivalDate
}

func (o *Transfer) GetCurrency() Currency {
	if o == nil {
		return Currency("")
	}
	return o.Currency
}

func (o *Transfer) GetDirection() Direction {
	if o == nil {
		return Direction("")
	}
	return o.Direction
}

func (o *Transfer) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Transfer) GetStatus() TransferStatus {
	if o == nil {
		return TransferStatus("")
	}
	return o.Status
}
