// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"push-cash/pkg/types"
)

// Transfer - Successful operation
type Transfer struct {
	// Amount of the transfer
	Amount int64 `json:"amount"`
	// Date the funds will arrive, formatted "YYYY-MM-DD"
	ArrivalDate types.Date `json:"arrival_date"`
	// Currency associated with the amount
	Currency Currency `json:"currency"`
	// Direction of the money
	Direction Direction `json:"direction"`
	// The unique identifier assigned by Push, prefix is "transfer_"
	ID     string         `json:"id"`
	Status TransferStatus `json:"status"`
}
