// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// User - User created successfully
type User struct {
	Address string `json:"address"`
	// Date and time in which user was first created in system
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	// Push's identifier assigned to the user
	ID   string `json:"id"`
	Kyc  Kyc    `json:"kyc"`
	Name string `json:"name"`
	// The array will be empty until the user completes their first transaction. Additional transactions will utilize stored payment credentials
	PaymentCredentials []PaymentCredential `json:"payment_credentials"`
	Phone              string              `json:"phone"`
	Status             UserStatus          `json:"status"`
	// the tag for the user
	Tag string `json:"tag"`
}
