// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type UserStatus string

const (
	UserStatusCreated       UserStatus = "created"
	UserStatusAuthenticated UserStatus = "authenticated"
	UserStatusActive        UserStatus = "active"
	UserStatusSuspended     UserStatus = "suspended"
)

func (e UserStatus) ToPointer() *UserStatus {
	return &e
}

func (e *UserStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "created":
		fallthrough
	case "authenticated":
		fallthrough
	case "active":
		fallthrough
	case "suspended":
		*e = UserStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserStatus: %v", v)
	}
}
