// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// User - User created successfully
type User struct {
	Address string `json:"address"`
	// Date and time in which user was first created in system
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	// Push's identifier assigned to the user
	ID   string `json:"id"`
	Kyc  Kyc    `json:"kyc"`
	Name string `json:"name"`
	// The array will be empty until the user completes their first transaction. Additional transactions will utilize stored payment credentials
	PaymentCredentials []PaymentCredential `json:"payment_credentials"`
	Phone              string              `json:"phone"`
	Status             UserStatus          `json:"status"`
	// the tag for the user
	Tag string `json:"tag"`
}

func (o *User) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *User) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *User) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *User) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *User) GetKyc() Kyc {
	if o == nil {
		return Kyc{}
	}
	return o.Kyc
}

func (o *User) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *User) GetPaymentCredentials() []PaymentCredential {
	if o == nil {
		return []PaymentCredential{}
	}
	return o.PaymentCredentials
}

func (o *User) GetPhone() string {
	if o == nil {
		return ""
	}
	return o.Phone
}

func (o *User) GetStatus() UserStatus {
	if o == nil {
		return UserStatus("")
	}
	return o.Status
}

func (o *User) GetTag() string {
	if o == nil {
		return ""
	}
	return o.Tag
}
